### ISSUE TITLE
why

### ISSUE THREAD

**Issue by icysun** [mvelazc0/PurpleSharp#1]
Why do I always prompt that my account or password is incorrect when I use purplesharp?
The remote local account password is correct

**Comment by mvelazc0** [comment]
Hello @icysun . Can you please share:

- The parameters you are using
- The error you are getting
- A screenshot would also help.

Thanks!

**Comment by mvelazc0** [comment]
Hey @icysun, checking in.

**Comment by icysun** [comment]
thanks，  i have a  try...
