### ISSUE TITLE
Error while running single technique id on local system

### ISSUE THREAD

**Issue by pravin-bug** [mvelazc0/PurpleSharp#12]
Hi @mvelazc0 ,

how are you?

can you please help me out is there any assembly need to load in PowerShell before executing the purple sharp? Because when I run purplesharp.exe /t technique-id, I am getting object reference not set error. Please find the attached error snapshot.

Please suggest
![C2DCDE17-1E0F-4352-8347-A4561B05496B](https://user-images.githubusercontent.com/125084135/218176640-aba6f067-4429-4b12-a74e-b12d5330fbb7.png)

**Comment by pravingit** [comment]
HI @mvelazc0 awaiting your valuable input. Please suggest..

**Comment by mvelazc0** [comment]
Hello @pravingit  ! Sorry for the delay.

This technique will try to query a domain to list computers and then scan them. If you are not running in a domain environment, it will fail like it did in your case. Are you running PurpleSharp from an AD domain computer ?

I think I should fix this to provide a better error. Thanks for pointing it out !

**Comment by mvelazc0** [comment]
Hey @pravingit @pravin-bug  , let me know if the answer made sense.
